Repository FreeProving/free-compiler, pull requests merged in 2020-07, with the labels that each got.

#103 Issue 95
  free-compiler.cabal
  src/lib/FreeC/Backend/Agda/Converter.hs
  src/lib/FreeC/Backend/Agda/Converter/FuncDecl.hs
  src/lib/FreeC/Backend/Agda/Converter/Type.hs
  src/lib/FreeC/Backend/Agda/Converter/TypeDecl.hs
  src/lib/FreeC/LiftedIR/Converter/Type.hs
  src/lib/FreeC/LiftedIR/Syntax/Type.hs
  src/test/FreeC/Backend/Agda/Converter/TypeDeclTests.hs
Labels: Agda, IR

#100 Spell Check Block 3
  src/lib/FreeC/IR/Inlining.hs
  src/lib/FreeC/Pipeline.hs
  src/lib/FreeC/Pretty.hs
  src/lib/FreeC/Util/Config.hs
  src/lib/FreeC/Util/Predicate.hs
  src/test/FreeC/Backend/Coq/Analysis/ConstantArgumentsTests.hs
  src/test/FreeC/Backend/Coq/Converter/ExprTests.hs
  src/test/FreeC/Backend/Coq/Converter/FuncDecl/NonRecTests.hs
  src/test/FreeC/Backend/Coq/Converter/FuncDecl/Rec/WithHelpersTests.hs
  src/test/FreeC/Backend/Coq/Converter/FuncDecl/Rec/WithSectionsTests.hs
  src/test/FreeC/Backend/Coq/Converter/TypeTests.hs
  src/test/FreeC/Backend/Coq/ConverterTests.hs
  src/test/FreeC/Backend/Coq/Tests.hs
  src/test/FreeC/PipelineTests.hs
Labels: documentation

#108 Implement a rudimentary sharing operator in Coq
  base/Free/Malias.v
Labels: Coq, enhancement

#113 Implement Injectable type class in Coq
  base/Free/Injectable.v
  base/Free/Instance/Comb.v
Labels: Coq, enhancement

#111 Implement Share and Choice effects
  base/Free.v
  base/Free/Instance/Comb.v
  base/Free/Instance/Identity.v
  base/Free/Instance/Maybe.v
  base/Free/Instance/ND.v
  base/Free/Instance/Share.v
Labels: Coq, enhancement

#122 Implement a tracing effect in Coq
  base/Free/Instance/ND.v
  base/Free/Instance/Trace.v
  base/Free/Util/Sharing.v
Labels: Coq, enhancement

#126 Add front- and backend abstractions and command line options
  CHANGELOG.md
  README.md
  free-compiler.cabal
  src/exe/FreeC/Application/Options.hs
  src/exe/FreeC/Application/Options/Descriptors.hs
  src/exe/FreeC/Backend.hs
  src/exe/FreeC/Backend.hs-boot
  src/exe/FreeC/Frontend.hs
  src/exe/FreeC/Frontend.hs-boot
  src/exe/Main.hs
  src/lib/FreeC/Backend/Coq/Converter/Module.hs
Labels: enhancement

#114 Issue 106: IR -> LIR -> Agda translations
  base/agda/Base/Extensionality.agda
  base/agda/Base/Free.agda
  base/agda/Base/Free/Instance/Identity/Properties.agda
  base/agda/Base/Free/Instance/Maybe.agda
  base/agda/Base/Free/Instance/Maybe/Properties.agda
  base/agda/Base/Partial.agda
  base/agda/Base/Prelude.agda
  free-compiler.cabal
  src/lib/FreeC/Backend/Agda/Base.hs
  src/lib/FreeC/Backend/Agda/Converter/Arg.hs
  src/lib/FreeC/Backend/Agda/Converter/Expr.hs
  src/lib/FreeC/Backend/Agda/Converter/Free.hs
  src/lib/FreeC/Backend/Agda/Converter/FuncDecl.hs
  src/lib/FreeC/Backend/Agda/Converter/Module.hs
  src/lib/FreeC/Backend/Agda/Converter/Type.hs
  src/lib/FreeC/Backend/Agda/Syntax.hs
  src/lib/FreeC/Environment/Fresh.hs
  src/lib/FreeC/Environment/LookupOrFail.hs
  src/lib/FreeC/Environment/ModuleInterface.hs
  src/lib/FreeC/Environment/ModuleInterface/Decoder.hs
  src/lib/FreeC/Environment/Renamer.hs
  src/lib/FreeC/LiftedIR/Converter/Expr.hs
  src/lib/FreeC/LiftedIR/Converter/Type.hs
  src/lib/FreeC/LiftedIR/Syntax/Expr.hs
  src/lib/FreeC/Pass/ExportPass.hs
  src/test/FreeC/Backend/Agda/Converter/FuncDeclTests.hs
Labels: Agda, IR, tests

#105 Complete spell check of block 5
  free-compiler.cabal
  src/lib/FreeC/Backend/Coq/Converter/FuncDecl/Rec/WithHelpers.hs
  src/lib/FreeC/Environment.hs
  src/lib/FreeC/Frontend/Haskell/Simplifier.hs
  src/lib/FreeC/Frontend/IR/Parser.hs
  src/lib/FreeC/IR/Reference.hs
  src/lib/FreeC/IR/Similar.hs
  src/lib/FreeC/IR/Strip.hs
  src/lib/FreeC/IR/Subst.hs
  src/lib/FreeC/IR/Syntax.hs
  src/lib/FreeC/IR/Syntax/Expr.hs
  src/lib/FreeC/IR/Syntax/FuncDecl.hs
  src/lib/FreeC/IR/Syntax/TypeScheme.hs
  src/lib/FreeC/IR/TypeScheme.hs
  src/lib/FreeC/Pass/KindCheckPass.hs
  src/lib/FreeC/Pass/ResolverPass.hs
  src/lib/FreeC/Pass/TypeInferencePass.hs
  src/lib/FreeC/Pass/TypeSignaturePass.hs
  src/test/FreeC/Frontend/IR/ParserTests.hs
  src/test/FreeC/IR/SimilarTests.hs
  src/test/FreeC/Test/Environment.hs
  src/test/FreeC/Test/Parser.hs
Labels: documentation

#117 Implement cbneed (sharing) operator
  base/Free/Malias.v
  base/Free/Monad.v
Labels: Coq, enhancement

#129 Issue 121: Expand Agda base library
  base/agda/Base/Prelude.agda
  base/agda/Base/Prelude/Bool.agda
  base/agda/Base/Prelude/Integer.agda
  base/agda/Base/Prelude/List.agda
  base/agda/Base/Prelude/Pair.agda
  base/agda/Base/Prelude/Unit.agda
  base/coq/Prelude.toml
  base/coq/Prelude/Integer.v
Labels: Agda, Coq

#143 Upgrade to Cabal 3.2.0.0
  .github/workflows/ci-pipeline.yml
  README.md
  free-compiler.cabal
  tool/full-test.sh
  tool/test.sh
Labels: CI, enhancement

#118 Implement effect handlers
  base/Free/Instance/Identity.v
  base/Free/Instance/Maybe.v
  base/Free/Instance/ND.v
  base/Free/Instance/Share.v
  base/Free/Instance/Trace.v
  base/Free/Malias.v
  base/Free/Test/SharingHandlerTests.v
  base/Free/Util/Search.v
  base/Free/Util/Sharing.v
Labels: Coq, enhancement

#138 Implement type classes for sharing and tracing
  base/Free.v
  base/Free/Class.v
  base/Free/Class/Injectable.v
  base/Free/Class/Partial.v
  base/Free/Class/Shareable.v
  base/Free/Class/Traceable.v
  base/Free/Instance/Trace.v
  base/Free/Malias.v
  base/Free/Verification/SharingHandlerTests.v
  base/Free/Verification/SharingProofs.v
Labels: Coq, enhancement

#139 Add support for infix data declarations
  src/lib/FreeC/Frontend/Haskell/Simplifier.hs
Labels: Haskell

#156 Let the compiler generate induction schemes
  base/Free.v
  base/Free/Tactic/ProveInd.v
  example/Proofs/AppendAssocProofs.v
  example/Queue/Queue.v
  src/lib/FreeC/Backend/Coq/Base.hs
  src/lib/FreeC/Backend/Coq/Converter/Arg.hs
  src/lib/FreeC/Backend/Coq/Converter/Free.hs
  src/lib/FreeC/Backend/Coq/Converter/TypeDecl.hs
  src/lib/FreeC/Environment/Renamer.hs
  src/test/FreeC/Backend/Coq/Converter/ExprTests.hs
  src/test/FreeC/Backend/Coq/Converter/FuncDecl/NonRecTests.hs
  src/test/FreeC/Backend/Coq/Converter/FuncDecl/Rec/WithHelpersTests.hs
  src/test/FreeC/Backend/Coq/Converter/FuncDecl/Rec/WithSectionsTests.hs
  src/test/FreeC/Backend/Coq/Converter/TypeDeclTests.hs
  src/test/FreeC/Environment/FreshTests.hs
Labels: Coq, enhancement

#141 Translate Coq Expressions using the lifted IR
  src/lib/FreeC/Backend/Agda/Converter/Expr.hs
  src/lib/FreeC/Backend/Agda/Converter/Free.hs
  src/lib/FreeC/Backend/Coq/Converter/Expr.hs
  src/lib/FreeC/Backend/Coq/Converter/Free.hs
  src/lib/FreeC/LiftedIR/Converter/Expr.hs
  src/lib/FreeC/LiftedIR/Syntax/Expr.hs
  src/test/FreeC/Backend/Agda/Converter/FuncDeclTests.hs
  src/test/FreeC/Backend/Coq/Converter/FuncDecl/NonRecTests.hs
  src/test/FreeC/Backend/Coq/Converter/FuncDecl/Rec/WithHelpersTests.hs
Labels: Coq, IR, enhancement

#161 Fix haddock of "Implement simple Let expressions"
  src/lib/FreeC/Backend/Coq/Analysis/ConstantArguments.hs
  src/lib/FreeC/Backend/Coq/Analysis/DecreasingArguments.hs
  src/lib/FreeC/Backend/Coq/Converter/FuncDecl/Rec/WithHelpers.hs
  src/lib/FreeC/Backend/Coq/Converter/FuncDecl/Rec/WithSections.hs
  src/lib/FreeC/Frontend/Haskell/Simplifier.hs
  src/lib/FreeC/Frontend/IR/Parser.hs
  src/lib/FreeC/Frontend/IR/Token.hs
  src/lib/FreeC/IR/Inlining.hs
  src/lib/FreeC/IR/Reference.hs
  src/lib/FreeC/IR/Similar.hs
  src/lib/FreeC/IR/Subst.hs
  src/lib/FreeC/IR/Subterm.hs
  src/lib/FreeC/IR/Syntax/Expr.hs
  src/lib/FreeC/LiftedIR/Converter/Expr.hs
  src/lib/FreeC/Pass/CompletePatternPass.hs
  src/lib/FreeC/Pass/EtaConversionPass.hs
  src/lib/FreeC/Pass/KindCheckPass.hs
  src/lib/FreeC/Pass/ResolverPass.hs
  src/lib/FreeC/Pass/TypeInferencePass.hs
  tool/make-docs.sh
Labels: CI
